version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - aws cloudformation package --template-file search-function.yaml --s3-bucket artifactbucket012425 --output-template-file gateway.yaml

artifacts:
  type: zip
  files:
    - search-function.yaml
    - gateway.yaml
