version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - aws cloudformation package --template-file Search Function/search-function.yaml --s3-bucket artifactbucket012425 --output-template-file Search Function/gateway.yaml

artifacts:
  type: zip
  files:
    - Search Function/search-function.yaml
    - Search Function/gateway.yaml
