AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources: https://artifactbucket012425.s3.us-east-1.amazonaws.com/opensearch_search_function/*
  searchgateway: https://c7u4ptxlec.execute-api.us-east-1.amazonaws.com/
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: sample.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::977765183651:role/lambda_s3_cloudformation_service_role'
